[package]
name = "expender"
version = "0.1.0"
authors = ["lyh_neo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
sha3 = "0.8.2"